# Generated by Django 6.0.1 on 2026-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('no_of_guests', models.SmallIntegerField(db_index=True)),
                ('booking_date', models.DateField()),
            ],
        ),
    ]
